AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloLambda
      CodeUri: src/endpoints/hello
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /test
            Method: get