AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloLambda
      CodeUri: src/endpoints/hello
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /test
            Method: get
  LoginLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LoginLambda
      CodeUri: src/endpoints/login
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          JWT_SECRET:
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /login
            Method: post
    