AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Simple Authorization
Parameters:
  ProjectName: 
    Type: String
    Description: Project Name
  SecretToken:
    Type: String
    NoEcho: true
    Description: The secret key used for signing jwt
Globals:
  Function:
    CodeUri: dist/endpoints
    Runtime: nodejs8.10
    Timeout: 30
Resources:
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub '${ProjectName}-Users'
      PrimaryKey:
        Name: email
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Tags:
      Project: !Ref ProjectName
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloLambda
      Handler: hello.handler
      MemorySize: 128 
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /test
            Method: get
  LoginLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LoginLambda
      Handler: login.handler
      MemorySize: 128 
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaDynamoDBExecutionRole
      Environment:
        Variables:
          JWT_SECRET: !Ref SecretToken
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /login
            Method: post
      Tags:
        Project: !Ref ProjectName
  RefreshLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RefreshLambda
      Handler: refresh.handler
      MemorySize: 128 
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          JWT_SECRET: !Ref SecretToken
      Events:
        MyEndpoint:
          Type: Api
          Properties:
            Path: /refresh
            Method: post
      Tags:
        Project: !Ref ProjectName